// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/on-finished/on-finished.d.ts
declare module 'on-finished' {

    function onFinished(msg:NodeJS.EventEmitter, listener:Function): NodeJS.EventEmitter;

    namespace onFinished {
        export function isFinished(msg:NodeJS.EventEmitter):boolean;
    }

    export = onFinished;
}
