// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/depd/depd.d.ts
declare module 'depd' {
    function depd(namespace: string): Deprecate;

    interface Deprecate {
        (message: string): void;
        function(fn: Function, message?: string): Function;
        property(obj: Object, prop: string, message: string): void;
    }

    export = depd;
}
